version: '3.8'

services:
  go-server:
    build: ./go-server
    ports:
      - "50051:50051"
    environment:
      - WHISPER_ENDPOINT=http://whisper:9083/inference
    networks:
      - whisper-net

  web-server:
    build: ./go-server
    command: /web-server
    ports:
      - "8080:8080"
    depends_on:
      - go-server
    networks:
      - whisper-net

  whisper:
    build: ./whisper-server
    ports:
      - "9083:9083" # Garantir mapeamento de portas
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:9083/health || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 5

  client:
    build: ./go-server
    command: /client -server go-server:50051
    depends_on:
      - go-server
    networks:
      - whisper-net

networks:
  whisper-net:
    driver: bridge
