version: '3.8'

services:
  go-server:
    build: ./go-server
    ports:
      - "50051:50051"
    environment:
      - WHISPER_ENDPOINT=http://whisper:9083/inference
    networks:
      - whisper-net

  web-server:
    build: ./go-server
    command: /web-server
    ports:
      - "8080:8080"
    depends_on:
      - go-server
    networks:
      - whisper-net

  whisper:
    build: ./whisper-server
    networks:
      - whisper-net

  client:
    build: ./go-server
    command: /client -server go-server:50051
    depends_on:
      - go-server
    networks:
      - whisper-net

networks:
  whisper-net:
    driver: bridge
